controller_joint_names: ['', 'front_left_steer_joint', 'front_left_wheel_joint', 'front_right_steer_joint', 'front_right_wheel_joint', 'steering_joint', 'rear_left_wheel_joint', 'rear_right_wheel_joint', ]
